@startuml Diagrama de Clases - AppModule

class AppModule {
    + imports: AuthModule, UsersModule, AuthorModule, BooksModule, BookReviewsModule, GenresModule, BookGenresModule, ShoppingCartModule, CatalogueBooksModule, PurchasesModule, LibraryBooksModule, BookContentModule
}

AppModule --> AuthModule
AppModule --> UsersModule
AppModule --> AuthorModule
AppModule --> BooksModule
AppModule --> BookReviewsModule
AppModule --> BookGenresModule
AppModule --> GenresModule
AppModule --> ShoppingCartModule
AppModule --> CatalogueBooksModule
AppModule --> PurchasesModule
AppModule --> LibraryBooksModule
AppModule --> BookContentModule

'Relaciones

AuthModule -- AuthController
AuthModule -- AuthService
AuthModule -- UsersModule

UsersModule -- UserController
UsersModule -- UserService
UsersModule -- UserEntity

AuthorModule -- AuthorController
AuthorModule -- AuthorService
AuthorModule -- AuthorEntity

BooksModule -- BooksController
BooksModule -- SettingsService
BooksModule -- BooksService
BooksModule -- BookEntity
BooksModule -- BookGenresEntity
BooksModule -- GenresEntity
BooksModule -- AuthorEntity

BookReviewsModule -- BookReviewsController
BookReviewsModule -- BookReviewsService
BookReviewsModule -- Review
BookReviewsModule -- User

BookGenresModule -- BookGenresController
BookGenresModule -- BookGenresSerice
BookGenresModule -- BookGenresEntity
BookGenresModule -- GenresEntity

GenresModule -- GenresController
GenresModule -- GenresService
GenresModule -- GenresEntity

ShoppingCartModule -- ShoppingCartController
ShoppingCartModule -- ShoppingCartService
ShoppingCartModule -- ShoppingCartBookEntity
ShoppingCartModule -- BookEntity
ShoppingCartModule -- UserEntity
ShoppingCartModule -- AuthorEntity

CatalogueBooksModule -- CatalogueBooksController
CatalogueBooksModule -- CatalogueBooksService
CatalogueBooksModule -- BooksModule

PurchasesModule -- PurchasesController
PurchasesModule -- PurchasesService
PurchasesModule -- PurchaseEntity
PurchasesModule -- ShoppingCartBookEntity
PurchasesModule -- BookEntity
PurchasesModule -- UserEntity
PurchasesModule -- AuthorEntity

LibraryBooksModule -- LibraryBooksController
LibraryBooksModule -- LibraryBooksService
LibraryBooksModule -- UserVirtualBooksEntity
LibraryBooksModule -- BooksModule

BookContentModule -- BookContentController
BookContentModule -- BookContentService
BookContentModule -- VirtualBookContentEntity

@enduml