import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/components/pages/Navbar";
import Footer from "@/components/pages/Footer";
import "./globals.css";

import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fedora = localFont({
  src: [
    {
      path: "../../public/Fonts/SF FEDORA/SFFedora.woff2",
      weight: "400",
      style: "normal",
    },
    /*{
      path: "./fonts/MiFuente-Bold.woff2",
      weight: "700",
      style: "normal",
    },*/
  ],
  variable: "--font-SF-Fedora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Biblioteca Virtual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${fedora.variable} antialiased cuerpo`}>
        <UserProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
