@startuml prueba

'======================
' Entidades
'======================

class AuthorEntity {
  + id: number
  + name: string
}

class BookGenresEntity {
  + id: number
  + id_book: number
  + id_genre: number
}

class BookEntity {
  + id: number
  + title: string
  + authorId: number
  + description: string
  + anio: number
  + isbn: string
  + image: string
  + stock: number
  + subscriber_exclusive: boolean
  + price: number
}

class GenreEntity {
  + id: number
  + name: string
}

class UserEntity {
  + id: number
  + username: string
  + email: string
}


'======================
' DTOs
'======================

package AuthDto {
  class LoginRequestBody {
    + email: string;
    + password: string;
  }

  class RegisterRequestBody {
    + username: string;
    + fistname: string;
    + lastname: string;
    + email: string;
    + image: string;
    + password: string;
  }
}

class CreateAuthorDto {
  + name: string;
}

class BookGenresDto {
  + id_book: number;
  + name: string;
}

class BookDto {
  + id: number;
  + title: string;
  + author: string;
  + author_id: number;
  + description: string;
  + genre: string[];
  + anio: number;
  + isbn: string;
  + image: string;
  + stock: number;
  + BookDTO2BookEntity(props): Book
  + BookEntity2BookDTO(props): BookDTO
}

class CreateGenreDto {
  + name: string
}

class CreateUserDto {
  + username: string
  + email: string
}


'======================
' Services
'======================

class AuthService {
  + register(requestBody: RegisterRequestBody)
  + login(requestBody: LoginRequestBody)
  + validateUser(email: string, pass: string): Promise<any>
}

class AuthorService {
  + create(createAuthorDto: CreateAuthorDto): Promise<Author>
  + findAll(): Promise<Author[]>
  + findOne(id: number): Promise<Author>
  + remove(id: number): Promise<void>
}

class BookGenresService {
  + findAll(): Promise<BookGenre[]>
  + create(data: Partial<BookGenreDto>): Promise<BookGenre>
  + delete(id: number)
}

class BookService {
  + findAll(): Promise<BookDTO[]>
  + findOne(id: number): Promise<BookDTO | null>
  + create(bookDTO: BookDTO)
  + update(id: number, bookDTO: BookDTO)
  + delete(id: number)
  + bookImageUrl = (imageName:string):string=>
}

class GenreService {
  + create(dto: CreateGenreDto)
  + findAll()
}

class UserService {
  + create(dto: CreateUserDto)
  + findAll()
}


'======================
' Controllers
'======================

class AuthController {
  + POST /login
  + POST /register
}

class AuthorController {
  + GET /authors
  + GET /authors/:id
  + POST /authors
  + DELETE /authors/:id
}

class BookGenresController {
  + GET /book_genres
  + POST /book_genres
  + DELETE /book_genres/:id
}

class BookController {
  + GET /books
  + GET /books/:id
  + POST /books
  + PUT /books/:id
  + DELETE /books/:id
}


class GenreController {
  + POST /genres
  + GET /genres
}

class UserController {
  + POST /users
  + GET /users
}

'======================
' EXTRAS
'======================


'======================
' Parte con AppModule corto (faltan agregar mas imports y relaciones.).

' class AppModule {
  '   + imports: BookModule, AuthorModule, GenreModule, UserModule
  '
' }

' AppModule --> BookModule
' AppModule --> AuthorModule
' AppModule --> GenreModule
' AppModule --> UserModule
' '======================


'======================
' Parte con AppModule completo.
' Como podemos apreciar el diagrama (y cuando probamos generar el png tambien) el diagrama queda dificil de leeer.

' class AppModule {
  '     + imports: AuthModule, UsersModule, AuthorModule, BooksModule, BookReviewsModule, GenresModule, BookGenresModule, ShoppingCartModule, CatalogueBooksModule, PurchasesModule, LibraryBooksModule, BookContentModule
  '
' }

' AppModule --> AuthModule
' AppModule --> UsersModule
' AppModule --> AuthorModule
' AppModule --> BooksModule
' AppModule --> BookReviewsModule
' AppModule --> GenresModule
' AppModule --> BookGenresModule
' AppModule --> ShoppingCartModule
' AppModule --> CatalogueBooksModule
' AppModule --> PurchasesModule
' AppModule --> LibraryBooksModule
' AppModule --> BookContentModule

'======================


'======================
' Relaciones
'======================

AuthController --> AuthService
AuthService --> AuthDto
' AuthService --> LoginRequestBody
' AuthService --> RegisterRequestBody

AuthorController --> AuthorService
AuthorService --> AuthorEntity
AuthorService --> CreateAuthorDto

BookGenresController --> BookGenresService
BookGenresService --> BookGenresEntity
BookGenresService --> GenreEntity
BookGenresService --> BookGenresDto


BookController --> BookService
BookService --> BookEntity
BookService --> BookDto
BookService --> UpdateBookDto

GenreController --> GenreService
GenreService --> GenreEntity
GenreService --> CreateGenreDto

UserController --> UserService
UserService --> UserEntity
UserService --> CreateUserDto


BookService --> GenreService : genreId
BookService --> AuthorService : authorId


@enduml
