@startuml

package carousel {
    class CarouselEntity  {
        - id: number
        - idBook: number
        - image: string = ""
    }

    class CarouselService {
        - settingsService: SettingsService
        - carouselRepository: Repository<Carousel>

        + findAll(): Promise<CarouselDTO[]>
        + create(body: CarouselDTO): Promise<CarouselDTO>
        + update(id: number, updateData: Partial<CarouselDTO>)
        + remove(id: number): Promise<void>
        + bookImageUrl = (imageName: string): string
    }

    class CarouselController {
        - carouselService: CarouselService

        + findAll(): Promise<CarouselDTO[]>
        + create(body: CarouselDTO, file: Express.Multer.File): Promise<CarouselDTO>
        + update(id: number, updateData: Partial<CarouselDTO>
        + remove(id: number): Promise<void>
    }

    class CarouselDTO {
        + id: number
        + idBook: number
        + image: string
    }
    
    class RepositoryC<<Carousel>> {

    }
}

package recommendations {
    class RecommendationsService {
        - recommendationsRepository: Repository<BookRecommendation>

        + findAll(): Promise<RecommendationDTO[]>
        + findOne(id: number): Promise<RecommendationDTO>
        + create(body: CreateRecommendationDTO): Promise<RecommendationDTO>
        + update(id:number, body: CreateRecommendationDTO): Promise<RecommendationDTO>
        + remove(id: number): Promise<void>
    }

    class RecommendationsController {
        - recommendationsService: RecomendationsService

        + findAll(): Promise<RecommendationDTO[]>
        + findOne(id: number): Promise<RecommendationDTO>
        + create(body: CreateRecommendationDTO): Promise<RecommendationDTO>
        + update(id: string, body: CreateRecommendationDTO): Promise<RecommendationDTO>
        + remove(id: number): Promise<void>
    }

    class RecommendationDTO {
        + id: number
        + idBook: number
        + title: string
        + author: string
        + image:string

        + RecommendationDTO(id:number, idBook: number, title: string, author:string, image:string)
    }

    class CreateRecommendationDTO {
        + idBook: number
    }

    class BookRecommendationEntity {
        - id: number
        + book: Book
    }

    class Repository<<Recommendation>> {

    }
}

' Relaciones
CarouselService ..> CarouselDTO : Usa/devuelve
CarouselController --> CarouselService : Depende de
CarouselService --> RepositoryC : Depende de
RepositoryC --> CarouselEntity : Accede a

RecommendationsService --> Repository : Depende de
Repository --> BookRecommendationEntity : Accede a
RecommendationsService ..> RecommendationDTO : Devuelve
RecommendationsService ..> CreateRecommendationDTO : Usa
RecommendationsController --> RecommendationsService : Depende de


@enduml