on: 
  pull_request:
    branches: [ "main", "Develop" ]
name: Test
jobs:
  defaults:
    runs-on: ubuntu-latest
    working-directory: ./backend
  test:
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Project Packages
        run: npm i

      - name: Run tests
        run: npm run test:cov