on: 
  pull_request:
    branches: [ "main", "Develop" ]
name: Test Coverage
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Project Packages
        run: npm i
        working-directory: ./backend

      - name: Run tests
        run: npm run test:cov
        working-directory: ./backend