on: 
  push:
    branches: [ "main", "Develop", "Testing" ]
  pull_request:
    branches: [ "main", "Develop" ]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Project Packages
        run: npm ci

      - name: Run tests
        run: npm run test